/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#fcf9f3",
        foreground: "#1c1c18",
        // Material-3 / Kindred Hope Design System
        primary: {
          DEFAULT: "#003b22",
          foreground: "#ffffff",
        },
        "primary-container": "#1a5336",
        "on-primary": "#ffffff",
        "on-primary-container": "#8cc5a0",
        "primary-fixed": "#b5f0c9",
        "primary-fixed-dim": "#99d4ae",
        "on-primary-fixed": "#002111",
        "on-primary-fixed-variant": "#175034",
        "inverse-primary": "#99d4ae",

        secondary: {
          DEFAULT: "#7f5700",
          foreground: "#ffffff",
        },
        "secondary-container": "#fdba45",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#6f4b00",
        "secondary-fixed": "#ffdeae",
        "secondary-fixed-dim": "#fdba45",
        "on-secondary-fixed": "#281900",
        "on-secondary-fixed-variant": "#604100",

        tertiary: {
          DEFAULT: "#24362e",
          foreground: "#ffffff",
        },
        "tertiary-container": "#3b4d44",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#a9bdb1",
        "tertiary-fixed": "#d3e7db",
        "tertiary-fixed-dim": "#b7cbbf",
        "on-tertiary-fixed": "#0d1f17",
        "on-tertiary-fixed-variant": "#384b41",

        surface: "#fcf9f3",
        "surface-bright": "#fcf9f3",
        "surface-dim": "#dcdad4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3ed",
        "surface-container": "#f0eee8",
        "surface-container-high": "#ebe8e2",
        "surface-container-highest": "#e5e2dc",
        "surface-variant": "#e5e2dc",
        "surface-tint": "#32694a",
        "on-surface": "#1c1c18",
        "on-surface-variant": "#404942",
        "inverse-surface": "#31312d",
        "inverse-on-surface": "#f3f0ea",

        outline: "#717972",
        "outline-variant": "#c0c9c0",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",

        muted: {
          DEFAULT: "#f0eee8",
          foreground: "#404942",
        },
        accent: {
          DEFAULT: "#fdba45",
          foreground: "#281900",
        },
        popover: {
          DEFAULT: "#ffffff",
          foreground: "#1c1c18",
        },
        card: {
          DEFAULT: "#ffffff",
          foreground: "#1c1c18",
        },

        // Backward compatibility colors
        'warm-orange': '#FF9A3D',
        'dark-navy': '#003566',
        'deep-blue': '#0066CC',
        'golden-yellow': '#FFD60A',
        'soft-white': '#FDFDFD',
        'light-gray': '#E9ECEF',
        'charcoal': '#1c1c18',
        'sage': '#1a5336',
        'terracotta': '#ba1a1a',
        'warm-white': '#fcf9f3',
        'soft-gray': '#f0eee8',
      },
      fontFamily: {
        display: ['Newsreader', 'Cormorant Garamond', 'serif'],
        body: ['"Plus Jakarta Sans"', '"DM Sans"', 'sans-serif'],
        "display-hero": ['Newsreader', 'serif'],
        "stat-counter": ['Newsreader', 'serif'],
        "headline-lg": ['Newsreader', 'serif'],
        "headline-md": ['Newsreader', 'serif'],
        "headline-sm": ['Newsreader', 'serif'],
        "body-lg": ['"Plus Jakarta Sans"', 'sans-serif'],
        "body-md": ['"Plus Jakarta Sans"', 'sans-serif'],
        "body-sm": ['"Plus Jakarta Sans"', 'sans-serif'],
        "label-lg": ['"Plus Jakarta Sans"', 'sans-serif'],
        "label-md": ['"Plus Jakarta Sans"', 'sans-serif'],
        "label-sm": ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-hero-mobile": ["38px", { lineHeight: "46px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-sm": ["22px", { lineHeight: "30px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "stat-counter": ["48px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-lg": ["15px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "700" }],
      },
      spacing: {
        margin: "3rem",
        gutter: "1.5rem",
        "space-xl": "3rem",
        "space-xs": "0.25rem",
        "gutter-mobile": "1rem",
        "margin-mobile": "1.25rem",
        "margin-tablet": "2rem",
        "space-md": "1rem",
        "space-lg": "1.75rem",
        "space-sm": "0.5rem",
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        card: '0 4px 20px -2px rgba(44,62,53,0.04)',
        'card-hover': '0 12px 36px -4px rgba(26,83,54,0.08), 0 4px 12px -2px rgba(217,155,38,0.06)',
        'btn-hover': '0 4px 16px rgba(26,83,54,0.25)',
        elevated: '0 12px 32px rgba(0,0,0,0.15)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(-5px)" },
          "50%": { transform: "translateY(5px)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "float": "float 3s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
